apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    namespace: tetris
    server: "https://kubernetes.default.svc"
  source:
    path: manifests/
    repoURL: "https://github.com/Chirag-ptel/Tf-Jenkins-Eks-Argo.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true